//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int DateDueType { get; set; }
        public int GracePeriod { get; set; }
        public decimal MinimumFinanceCharge { get; set; }
        public double AnnualInterestRate { get; set; }
        public bool ApplyFinanceChargesOnFinanceCharges { get; set; }
        public decimal MinimumPayment { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public string Code { get; set; }
        public int HQID { get; set; }
    }
}
