//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alias
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string Alias1 { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
