//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARHistoryMirror
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int LocalARHistoryType { get; set; }
        public int RemoteStoreID { get; set; }
        public int RemoteARID { get; set; }
        public int RemotePaymentID { get; set; }
        public decimal Payment { get; set; }
        public bool IsProcessed { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
