//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int UserID { get; set; }
        public int Operation { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string AdditionalInfo { get; set; }
        public System.DateTime DBDateTime { get; set; }
    }
}
