//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int CashierID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Text { get; set; }
        public bool ReminderEnabled { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public bool IsPersonal { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
