//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier
    {
        public int HQID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Number { get; set; }
        public int StoreID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public decimal FloorLimit { get; set; }
        public decimal ReturnLimit { get; set; }
        public short CashDrawerNumber { get; set; }
        public short SecurityLevel { get; set; }
        public int Privileges { get; set; }
        public string EmailAddress { get; set; }
        public int FailedLogonAttempts { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public decimal MaxOverShortAmount { get; set; }
        public double MaxOverShortPercent { get; set; }
        public int OverShortLimitType { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> PasswordChangedDate { get; set; }
        public bool PasswordResetFlag { get; set; }
        public bool Inactive { get; set; }
        public int POSTaskpad { get; set; }
    }
}
