//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string AccountNumber { get; set; }
        public int AccountTypeID { get; set; }
        public string Address2 { get; set; }
        public bool AssessFinanceCharges { get; set; }
        public string Company { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public Nullable<System.DateTime> CustomDate5 { get; set; }
        public double CustomNumber1 { get; set; }
        public double CustomNumber2 { get; set; }
        public double CustomNumber3 { get; set; }
        public double CustomNumber4 { get; set; }
        public double CustomNumber5 { get; set; }
        public string CustomText1 { get; set; }
        public string CustomText2 { get; set; }
        public string CustomText3 { get; set; }
        public string CustomText4 { get; set; }
        public string CustomText5 { get; set; }
        public bool GlobalCustomer { get; set; }
        public int HQID { get; set; }
        public Nullable<System.DateTime> LastStartingDate { get; set; }
        public Nullable<System.DateTime> LastClosingDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool LimitPurchase { get; set; }
        public decimal LastClosingBalance { get; set; }
        public int PrimaryShipToID { get; set; }
        public string State { get; set; }
        public int StoreID { get; set; }
        public int ID { get; set; }
        public bool LayawayCustomer { get; set; }
        public bool Employee { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public decimal AccountBalance { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal TotalSales { get; set; }
        public System.DateTime AccountOpened { get; set; }
        public System.DateTime LastVisit { get; set; }
        public int TotalVisits { get; set; }
        public decimal TotalSavings { get; set; }
        public float CurrentDiscount { get; set; }
        public short PriceLevel { get; set; }
        public bool TaxExempt { get; set; }
        public string Notes { get; set; }
        public string Title { get; set; }
        public string EmailAddress { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public string TaxNumber { get; set; }
        public string PictureName { get; set; }
        public int DefaultShippingServiceID { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public int CashierID { get; set; }
        public int SalesRepID { get; set; }
        public decimal Vouchers { get; set; }
    }
}
