//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseMetaData
    {
        public int ID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValueEx { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
