//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropPayout
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int BatchNumber { get; set; }
        public System.DateTime Time { get; set; }
        public int CashierID { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public string Recipient { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int ReasonCodeID { get; set; }
    }
}
