//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicsOnlineAuthorization
    {
        public int ID { get; set; }
        public Nullable<int> TenderEntryId { get; set; }
        public string DynamicsOnlineTransactionId { get; set; }
        public string ResponseApprovalCode { get; set; }
        public Nullable<int> AuthorizationStatus { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public Nullable<int> SettlementStatus { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<bool> TransactionRecalled { get; set; }
        public string AuthResponse { get; set; }
    }
}
