//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public int ID { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string ProcessorCode { get; set; }
        public string Data { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
    }
}
