//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalRequestlog
    {
        public decimal RequestID { get; set; }
        public string RequestType { get; set; }
        public Nullable<decimal> VoucherOnlineID { get; set; }
        public Nullable<decimal> Register { get; set; }
        public Nullable<decimal> StoreID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> ErrorCode { get; set; }
        public Nullable<decimal> ItemHQID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte[] DBtimeStamp { get; set; }
    }
}
