//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryOffline
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int ItemID { get; set; }
        public int DetailID { get; set; }
        public int ReasonCodeID { get; set; }
        public double Quantity { get; set; }
        public string Comment { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int PurchaseOrderID { get; set; }
        public System.DateTime Date { get; set; }
    }
}
