using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace POS_DataLayer
{
    class ItemMetadata
    {
        private const string _BinLocation ="";
        private const decimal _BuydownPrice =0;
        private const double _BuydownQuantity =0;
        private const decimal _CommissionAmount =0;
        private const decimal _CommissionMaximum =0;
        private const int _CommissionMode =0;
        private const float _CommissionPercentProfit =0;
        private const float _CommissionPercentSale =0;
        private const string _Description ="";
        private const bool _FoodStampable =false;
        private const int _HQID =0;
        private const bool _ItemNotDiscountable =false;
       
        private const string _Notes ="";
        private const double _QuantityCommitted =0;
        private const int _SerialNumberCount =0;
        private const double _TareWeightPercent =0;
        private const int _ID =0;
        private const string _ItemLookupCode ="";
        private const int _DepartmentID =0;
        private const int _CategoryID =0;
        private const int _MessageID =0;
        private const decimal _Price =0;
        private const decimal _PriceA =0;
        private const decimal _PriceB =0;
        private const decimal _PriceC =0;
        private const decimal _SalePrice =0;
       
        private const int _QuantityDiscountID =0;
        private const int _TaxID =0;
        private const short _ItemType =0;
        private const decimal _Cost =0;
        private const double _Quantity =0;
        private const double _ReorderPoint =0;
        private const double _RestockLevel =0;
        private const double _TareWeight =0;
        private const int _SupplierID =0;
        private const int _TagAlongItem =0;
        private const double _TagAlongQuantity =0;
        private const int __ParentItem =0;
        private const double _ParentQuantity =0;
        private const short _BarcodeFormat =0;
        private const decimal _PriceLowerBound =0;
        private const decimal _PriceUpperBound =0;
        private const string _PictureName ="";
        
        private const string _ExtendedDescription ="";
        private const string _SubDescription1 ="";
        private const string _SubDescription2 ="";
        private const string _SubDescription3 ="";
        private const string _UnitOfMeasure ="";
        private const int _SubCategoryID =0;
        private const bool _QuantityEntryNotAllowed =false;
        private const bool _PriceMustBeEntered =false;
        private const string _BlockSalesReason ="";
        
        private const double _Weight =0;
        private const bool _Taxable =false;
       // private const byte[] _DBTimeStamp =0;
        
        private const decimal _LastCost =0;
        private const decimal _ReplacementCost =0;
        private const bool _WebItem =false;
        private const int _BlockSalesType =0;
        private const int _BlockSalesScheduleID =0;
        private const int _SaleType =0;
        private const int _SaleScheduleID =0;
        private const bool _Consignment =false;
        private const bool _Inactive =false;
        
        private const bool _DoNotOrder =false;
        private const decimal _MSRP =0;
       
        private const string _Content ="";
        private const string _UsuallyShip ="";
        private const string _NumberFormat ="";
        private const bool _ItemCannotBeRet =false;
        private const bool _ItemCannotBeSold =false;
        private const bool _IsAutogenerated =false;
        private const bool _IsGlobalvoucher =false;
        private const bool _DeleteZeroBalanceEntry =false;
        private const int _TenderID =0;







        [DefaultValue("")]
        public string BinLocation { get; set; }
        [DefaultValue("0")]
        public decimal BuydownPrice { get; set; }
        [DefaultValue("0")]
        public double BuydownQuantity { get; set; }
        [DefaultValue("0")]
        public decimal CommissionAmount { get; set; }
        [DefaultValue("0")]
        public decimal CommissionMaximum { get; set; }
        [DefaultValue("0")]
        public int CommissionMode { get; set; }
        [DefaultValue("0")]
        public float CommissionPercentProfit { get; set; }
        [DefaultValue("0")]
        public float CommissionPercentSale { get; set; }
        [DefaultValue("0")]
        public string Description { get; set; }
        [DefaultValue("0")]
        public bool FoodStampable { get; set; }
        [DefaultValue("0")]
        public int HQID { get; set; }
        [DefaultValue("0")]
        public bool ItemNotDiscountable { get; set; }

        public Nullable<System.DateTime> LastReceived { get; set; }

        public System.DateTime? LastUpdated { get; set; }
        [DefaultValue("")]
        public string Notes { get; set; }
        [DefaultValue("0")]
        public double QuantityCommitted { get; set; }
        [DefaultValue("0")]
        public int SerialNumberCount { get; set; }
        [DefaultValue("0")]
        public double TareWeightPercent { get; set; }

        public int ID { get; set; }
        [DefaultValue("")]
        public string ItemLookupCode { get; set; }
        [DefaultValue("0")]
        public int DepartmentID { get; set; }
        [DefaultValue("0")]
        public int CategoryID { get; set; }
        [DefaultValue("0")]
        public int MessageID { get; set; }
        [DefaultValue("0")]
        public decimal Price { get; set; }
        [DefaultValue("0")]
        public decimal PriceA { get; set; }
        [DefaultValue("0")]
        public decimal PriceB { get; set; }
        [DefaultValue("0")]
        public decimal PriceC { get; set; }
        [DefaultValue("0")]
        public decimal SalePrice { get; set; }

        public Nullable<System.DateTime> SaleStartDate { get; set; }

        public Nullable<System.DateTime> SaleEndDate { get; set; }

        public int QuantityDiscountID { get; set; }
        [DefaultValue("0")]
        public int TaxID { get; set; }
        [DefaultValue("0")]
        public short ItemType { get; set; }
        [DefaultValue("0")]
        public decimal Cost { get; set; }
        [DefaultValue("0")]
        public double Quantity { get; set; }
        [DefaultValue("0")]
        public double ReorderPoint { get; set; }
        [DefaultValue("0")]
        public double RestockLevel { get; set; }
        [DefaultValue("0")]
        public double TareWeight { get; set; }
        [DefaultValue("0")]
        public int SupplierID { get; set; }
        [DefaultValue("0")]
        public int TagAlongItem { get; set; }
        [DefaultValue("0")]
        public double TagAlongQuantity { get; set; }
        [DefaultValue("0")]
        public int ParentItem { get; set; }
        [DefaultValue("0")]
        public double ParentQuantity { get; set; }
        [DefaultValue("0")]
        public short BarcodeFormat { get; set; }
        [DefaultValue("0")]
        public decimal PriceLowerBound { get; set; }
        [DefaultValue("0")]
        public decimal PriceUpperBound { get; set; }
        [DefaultValue("0")]
        public string PictureName { get; set; }

        public Nullable<System.DateTime> LastSold { get; set; }
        [DefaultValue("")]
        public string ExtendedDescription { get; set; }
        [DefaultValue("")]
        public string SubDescription1 { get; set; }
        [DefaultValue("")]
        public string SubDescription2 { get; set; }
        [DefaultValue("")]
        public string SubDescription3 { get; set; }
        [DefaultValue("")]
        public string UnitOfMeasure { get; set; }
        [DefaultValue("0")]
        public int SubCategoryID { get; set; }
        [DefaultValue("0")]
        public bool QuantityEntryNotAllowed { get; set; }
        [DefaultValue("0")]
        public bool PriceMustBeEntered { get; set; }
        [DefaultValue("")]
        public string BlockSalesReason { get; set; }

        public Nullable<System.DateTime> BlockSalesAfterDate { get; set; }
        [DefaultValue("0")]
        public double Weight { get; set; }
        [DefaultValue("0")]
        public bool Taxable { get; set; }

        public byte[] DBTimeStamp { get; set; }

        public Nullable<System.DateTime> BlockSalesBeforeDate { get; set; }
        [DefaultValue("0")]
        public decimal LastCost { get; set; }
        [DefaultValue("0")]
        public decimal ReplacementCost { get; set; }
        [DefaultValue("0")]
        public bool WebItem { get; set; }
        [DefaultValue("0")]
        public int BlockSalesType { get; set; }
        [DefaultValue("0")]
        public int BlockSalesScheduleID { get; set; }
        [DefaultValue("0")]
        public int SaleType { get; set; }
        [DefaultValue("0")]
        public int SaleScheduleID { get; set; }
        [DefaultValue("0")]
        public bool Consignment { get; set; }
        [DefaultValue("0")]
        public bool Inactive { get; set; }

        public Nullable<System.DateTime> LastCounted { get; set; }
        [DefaultValue("0")]
        public bool DoNotOrder { get; set; }
        [DefaultValue("0")]
        public decimal MSRP { get; set; }

        public System.DateTime? DateCreated { get; set; }
        [DefaultValue("")]
        public string Content { get; set; }
        [DefaultValue("")]
        public string UsuallyShip { get; set; }
        [DefaultValue("")]
        public string NumberFormat { get; set; }
        public Nullable<bool> ItemCannotBeRet { get; set; }
        public Nullable<bool> ItemCannotBeSold { get; set; }
        public Nullable<bool> IsAutogenerated { get; set; }
        [DefaultValue("0")]
        public bool IsGlobalvoucher { get; set; }
        public Nullable<bool> DeleteZeroBalanceEntry { get; set; }
        [DefaultValue("0")]
        public int TenderID { get; set; }
    }
}
