//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClassComponent
    {
        public int ID { get; set; }
        public int ItemClassID { get; set; }
        public int ItemID { get; set; }
        public double Quantity { get; set; }
        public string Detail1 { get; set; }
        public string Detail2 { get; set; }
        public string Detail3 { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public decimal Price { get; set; }
    }
}
