//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string BinLocation { get; set; }
        public decimal BuydownPrice { get; set; }
        public double BuydownQuantity { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal CommissionMaximum { get; set; }
        public int CommissionMode { get; set; }
        public float CommissionPercentProfit { get; set; }
        public float CommissionPercentSale { get; set; }
        public string Description { get; set; }
        public bool FoodStampable { get; set; }
        public int HQID { get; set; }
        public bool ItemNotDiscountable { get; set; }
        public Nullable<System.DateTime> LastReceived { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Notes { get; set; }
        public double QuantityCommitted { get; set; }
        public int SerialNumberCount { get; set; }
        public double TareWeightPercent { get; set; }
        public int ID { get; set; }
        public string ItemLookupCode { get; set; }
        public int DepartmentID { get; set; }
        public int CategoryID { get; set; }
        public int MessageID { get; set; }
        public decimal Price { get; set; }
        public decimal PriceA { get; set; }
        public decimal PriceB { get; set; }
        public decimal PriceC { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<System.DateTime> SaleStartDate { get; set; }
        public Nullable<System.DateTime> SaleEndDate { get; set; }
        public int QuantityDiscountID { get; set; }
        public int TaxID { get; set; }
        public short ItemType { get; set; }
        public decimal Cost { get; set; }
        public double Quantity { get; set; }
        public double ReorderPoint { get; set; }
        public double RestockLevel { get; set; }
        public double TareWeight { get; set; }
        public int SupplierID { get; set; }
        public int TagAlongItem { get; set; }
        public double TagAlongQuantity { get; set; }
        public int ParentItem { get; set; }
        public double ParentQuantity { get; set; }
        public short BarcodeFormat { get; set; }
        public decimal PriceLowerBound { get; set; }
        public decimal PriceUpperBound { get; set; }
        public string PictureName { get; set; }
        public Nullable<System.DateTime> LastSold { get; set; }
        public string ExtendedDescription { get; set; }
        public string SubDescription1 { get; set; }
        public string SubDescription2 { get; set; }
        public string SubDescription3 { get; set; }
        public string UnitOfMeasure { get; set; }
        public int SubCategoryID { get; set; }
        public bool QuantityEntryNotAllowed { get; set; }
        public bool PriceMustBeEntered { get; set; }
        public string BlockSalesReason { get; set; }
        public Nullable<System.DateTime> BlockSalesAfterDate { get; set; }
        public double Weight { get; set; }
        public bool Taxable { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public Nullable<System.DateTime> BlockSalesBeforeDate { get; set; }
        public decimal LastCost { get; set; }
        public decimal ReplacementCost { get; set; }
        public bool WebItem { get; set; }
        public int BlockSalesType { get; set; }
        public int BlockSalesScheduleID { get; set; }
        public int SaleType { get; set; }
        public int SaleScheduleID { get; set; }
        public bool Consignment { get; set; }
        public bool Inactive { get; set; }
        public Nullable<System.DateTime> LastCounted { get; set; }
        public bool DoNotOrder { get; set; }
        public decimal MSRP { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Content { get; set; }
        public string UsuallyShip { get; set; }
        public string NumberFormat { get; set; }
        public Nullable<bool> ItemCannotBeRet { get; set; }
        public Nullable<bool> ItemCannotBeSold { get; set; }
        public Nullable<bool> IsAutogenerated { get; set; }
        public bool IsGlobalvoucher { get; set; }
        public Nullable<bool> DeleteZeroBalanceEntry { get; set; }
        public int TenderID { get; set; }
    }
}
