//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClass
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public short Dimensions { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string Title3 { get; set; }
        public short ClassType { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public bool UseComponentPrice { get; set; }
        public int HQID { get; set; }
        public string ItemLookupCode { get; set; }
        public string Notes { get; set; }
        public int DepartmentID { get; set; }
        public int CategoryID { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public int SupplierID { get; set; }
        public short BarcodeFormat { get; set; }
        public string SubDescription1 { get; set; }
        public string SubDescription2 { get; set; }
        public string SubDescription3 { get; set; }
        public int TaxID { get; set; }
    }
}
