//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTax
    {
        public int HQID { get; set; }
        public int ID { get; set; }
        public string Description { get; set; }
        public int Options { get; set; }
        public int TaxID01 { get; set; }
        public bool ShowOnReceipt01 { get; set; }
        public int TaxID02 { get; set; }
        public bool ShowOnReceipt02 { get; set; }
        public int TaxID03 { get; set; }
        public bool ShowOnReceipt03 { get; set; }
        public int TaxID04 { get; set; }
        public bool ShowOnReceipt04 { get; set; }
        public int TaxID05 { get; set; }
        public bool ShowOnReceipt05 { get; set; }
        public int TaxID06 { get; set; }
        public bool ShowOnReceipt06 { get; set; }
        public int TaxID07 { get; set; }
        public bool ShowOnReceipt07 { get; set; }
        public int TaxID08 { get; set; }
        public bool ShowOnReceipt08 { get; set; }
        public int TaxID09 { get; set; }
        public bool ShowOnReceipt09 { get; set; }
        public int TaxID10 { get; set; }
        public bool ShowOnReceipt10 { get; set; }
        public string Code { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
