//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacroEvent
    {
        public int ID { get; set; }
        public int MacroID { get; set; }
        public int Message { get; set; }
        public int ParamL { get; set; }
        public int ParamH { get; set; }
        public int Time { get; set; }
        public int hWnd { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
