//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixAttributeDisplayOrder
    {
        public int ID { get; set; }
        public int ItemClassID { get; set; }
        public int Dimension { get; set; }
        public string Attribute { get; set; }
        public string Code { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool Inactive { get; set; }
        public int HQID { get; set; }
    }
}
