//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int StoreID { get; set; }
        public int ID { get; set; }
        public bool Closed { get; set; }
        public System.DateTime Time { get; set; }
        public int Type { get; set; }
        public string Comment { get; set; }
        public int CustomerID { get; set; }
        public int ShipToID { get; set; }
        public bool DepositOverride { get; set; }
        public decimal Deposit { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime ExpirationOrDueDate { get; set; }
        public bool Taxable { get; set; }
        public int SalesRepID { get; set; }
        public string ReferenceNumber { get; set; }
        public decimal ShippingChargeOnOrder { get; set; }
        public bool ShippingChargeOverride { get; set; }
        public int ShippingServiceID { get; set; }
        public string ShippingTrackingNumber { get; set; }
        public string ShippingNotes { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int ReasonCodeID { get; set; }
        public int ExchangeID { get; set; }
        public int ChannelType { get; set; }
        public int DefaultDiscountReasonCodeID { get; set; }
        public int DefaultReturnReasonCodeID { get; set; }
        public int DefaultTaxChangeReasonCodeID { get; set; }
    }
}
