//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalInventoryEntry
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int PhysicalInventoryID { get; set; }
        public int ReasonCodeID { get; set; }
        public Nullable<System.DateTime> CountTime { get; set; }
        public int ItemID { get; set; }
        public string BinLocation { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public double QuantityCounted { get; set; }
        public double QuantitySold { get; set; }
        public double QuantityReturned { get; set; }
        public double QuantityXferIn { get; set; }
        public double QuantityXferOut { get; set; }
        public double QuantityAdjusted { get; set; }
        public double QuantityToOffline { get; set; }
        public double QuantityFromOffline { get; set; }
        public double QuantityRefreshed { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
