//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalInventory
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> LastRefresh { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
