//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoleDisplayMessage
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string MessageLine1 { get; set; }
        public short EffectLine1 { get; set; }
        public short UpdateRateLine1 { get; set; }
        public bool DateAndTimeLine1 { get; set; }
        public short ScrollChangeSizeLine1 { get; set; }
        public string MessageLine2 { get; set; }
        public short EffectLine2 { get; set; }
        public short UpdateRateLine2 { get; set; }
        public bool DateAndTimeLine2 { get; set; }
        public short ScrollChangeSizeLine2 { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int StoreID { get; set; }
    }
}
