//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRounding
    {
        public int ID { get; set; }
        public int HQID { get; set; }
        public decimal PriceFrom { get; set; }
        public decimal PriceTo { get; set; }
        public bool UseMultipleOfRule { get; set; }
        public decimal MultipleOf { get; set; }
        public bool UseEndsInRule { get; set; }
        public decimal EndsIn { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
