//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderEntry
    {
        public string ItemDescription { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public double QuantityReceivedToDate { get; set; }
        public int StoreID { get; set; }
        public int ID { get; set; }
        public int PurchaseOrderID { get; set; }
        public double QuantityOrdered { get; set; }
        public double QuantityReceived { get; set; }
        public int ItemID { get; set; }
        public string OrderNumber { get; set; }
        public decimal Price { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public double TaxRate { get; set; }
        public int InventoryOfflineID { get; set; }
        public decimal ShippingPerItem { get; set; }
        public decimal OtherFeesPerItem { get; set; }
        public double LastQuantityReceived { get; set; }
        public Nullable<System.DateTime> LastReceivedDate { get; set; }
    }
}
