//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderEntryDetail
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int PurchaseOrderEntryID { get; set; }
        public System.DateTime Date { get; set; }
        public short Status { get; set; }
        public int SerialID { get; set; }
        public string SerialNumber1 { get; set; }
        public string SerialNumber2 { get; set; }
        public string SerialNumber3 { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int InventoryOfflineID { get; set; }
    }
}
