//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public System.DateTime LastUpdated { get; set; }
        public string POTitle { get; set; }
        public int POType { get; set; }
        public int StoreID { get; set; }
        public int WorksheetID { get; set; }
        public int ID { get; set; }
        public string PONumber { get; set; }
        public short Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string To { get; set; }
        public string ShipTo { get; set; }
        public string Requisitioner { get; set; }
        public string ShipVia { get; set; }
        public string FOBPoint { get; set; }
        public string Terms { get; set; }
        public float TaxRate { get; set; }
        public decimal Shipping { get; set; }
        public string Freight { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string ConfirmingTo { get; set; }
        public string Remarks { get; set; }
        public int SupplierID { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int OtherStoreID { get; set; }
        public int CurrencyID { get; set; }
        public double ExchangeRate { get; set; }
        public int OtherPOID { get; set; }
        public int InventoryLocation { get; set; }
        public bool IsPlaced { get; set; }
        public Nullable<System.DateTime> DatePlaced { get; set; }
        public int BatchNumber { get; set; }
        public decimal EstShipping { get; set; }
        public decimal CurrentShipping { get; set; }
        public decimal EstOtherFees { get; set; }
        public decimal CurrentOtherFees { get; set; }
        public decimal OtherFees { get; set; }
        public int CostDistributionMethod { get; set; }
        public int ParentPOId { get; set; }
        public int RootPOId { get; set; }
        public int OriginPOId { get; set; }
        public string MasterPO { get; set; }
        public int DiscrepancyStatus { get; set; }
    }
}
