//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityDiscount
    {
        public string Description { get; set; }
        public int HQID { get; set; }
        public int ID { get; set; }
        public bool DiscountOddItems { get; set; }
        public double Quantity1 { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price1A { get; set; }
        public decimal Price1B { get; set; }
        public decimal Price1C { get; set; }
        public double Quantity2 { get; set; }
        public decimal Price2 { get; set; }
        public decimal Price2A { get; set; }
        public decimal Price2B { get; set; }
        public decimal Price2C { get; set; }
        public double Quantity3 { get; set; }
        public decimal Price3 { get; set; }
        public decimal Price3A { get; set; }
        public decimal Price3B { get; set; }
        public decimal Price3C { get; set; }
        public double Quantity4 { get; set; }
        public decimal Price4 { get; set; }
        public decimal Price4A { get; set; }
        public decimal Price4B { get; set; }
        public decimal Price4C { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int Type { get; set; }
        public double PercentOffPrice1 { get; set; }
        public double PercentOffPrice1A { get; set; }
        public double PercentOffPrice1B { get; set; }
        public double PercentOffPrice1C { get; set; }
        public double PercentOffPrice2 { get; set; }
        public double PercentOffPrice2A { get; set; }
        public double PercentOffPrice2B { get; set; }
        public double PercentOffPrice2C { get; set; }
        public double PercentOffPrice3 { get; set; }
        public double PercentOffPrice3A { get; set; }
        public double PercentOffPrice3B { get; set; }
        public double PercentOffPrice3C { get; set; }
        public double PercentOffPrice4 { get; set; }
        public double PercentOffPrice4A { get; set; }
        public double PercentOffPrice4B { get; set; }
        public double PercentOffPrice4C { get; set; }
    }
}
