//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string TemplateCancel { get; set; }
        public string TemplateDrop { get; set; }
        public string TemplateLayaway { get; set; }
        public string TemplatePayment { get; set; }
        public string TemplatePayout { get; set; }
        public string TemplateQuote { get; set; }
        public string TemplateSale { get; set; }
        public string TemplateWorkOrder { get; set; }
        public string TemplateReport { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int StoreID { get; set; }
    }
}
