//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordDeletedLog
    {
        public string TableName { get; set; }
        public string IDFieldName { get; set; }
        public int RecordID { get; set; }
        public System.DateTime WhenDeleted { get; set; }
        public int StoreID { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int ID { get; set; }
    }
}
