//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public string Description { get; set; }
        public bool PoleDisplayEnabled { get; set; }
        public int Receipt2ID { get; set; }
        public bool ScaleEnabled { get; set; }
        public double ScaleTimeout { get; set; }
        public bool ScannerEnabled { get; set; }
        public int ZZBatchNumber { get; set; }
        public int ID { get; set; }
        public short Number { get; set; }
        public int CurrentBatchNumber { get; set; }
        public int Receipt1ID { get; set; }
        public int PoleDisplayMessageID { get; set; }
        public string Printer1Name { get; set; }
        public int Printer1Options { get; set; }
        public string Printer2Name { get; set; }
        public int Printer2Options { get; set; }
        public int ChannelID { get; set; }
        public bool NetDisplayEnabled { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int DefaultPriceLevel { get; set; }
        public string PoleDisplayName { get; set; }
        public string ScaleName { get; set; }
        public string ScannerName { get; set; }
        public int Printer1Type { get; set; }
        public int Printer2Type { get; set; }
        public string CashDrawer1Name { get; set; }
        public bool CashDrawer1Enabled { get; set; }
        public bool CashDrawer1WaitForClose { get; set; }
        public int CashDrawer1OpenTimeout { get; set; }
        public string CashDrawer2Name { get; set; }
        public bool CashDrawer2Enabled { get; set; }
        public bool CashDrawer2WaitForClose { get; set; }
        public int CashDrawer2OpenTimeout { get; set; }
        public int StoreID { get; set; }
        public string MICRName { get; set; }
        public bool MICREnabled { get; set; }
        public double MICRTimeout { get; set; }
        public string MSRName { get; set; }
        public bool MSREnabled { get; set; }
        public string SignatureCaptureName { get; set; }
        public bool SignatureCaptureEnabled { get; set; }
        public string SignatureCaptureFormName { get; set; }
        public bool TouchScreenEnabled { get; set; }
        public int KeyboardID { get; set; }
        public int DefaultServiceID { get; set; }
        public bool PINPadEnabled { get; set; }
        public string PINPadName { get; set; }
        public string PINPadSystem { get; set; }
        public int TransactionHost { get; set; }
        public bool RealTimeSigCap { get; set; }
        public int Printer1GiftOptions { get; set; }
        public int Printer2GiftOptions { get; set; }
        public int POSTaskpad { get; set; }
    }
}
