//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string ReportFilename { get; set; }
        public string Description { get; set; }
        public string Settings { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int StoreID { get; set; }
    }
}
