//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RR_AppKey
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public float Version { get; set; }
        public int Data1 { get; set; }
        public int Data2 { get; set; }
        public int Data3 { get; set; }
        public Nullable<System.DateTime> KeyDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string ExtData { get; set; }
    }
}
