//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RR_LoginData
    {
        public int LoginID { get; set; }
        public int ID { get; set; }
        public byte Type { get; set; }
        public byte Number { get; set; }
        public string Text { get; set; }
        public string Data { get; set; }
        public string formName { get; set; }
    }
}
