//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleSegment
    {
        public int ID { get; set; }
        public int HQID { get; set; }
        public int ScheduleID { get; set; }
        public int StartDay { get; set; }
        public int EndDay { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
