//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int ID { get; set; }
        public string FormName { get; set; }
        public string ClassName { get; set; }
        public string ControlType { get; set; }
        public string ControlName { get; set; }
        public int ControlIndex { get; set; }
        public int ReadDisableCode { get; set; }
        public int ChangeDisableCode { get; set; }
        public string ColumnTitle { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int StoreID { get; set; }
    }
}
