//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serial
    {
        public int HQID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SerialNumber2 { get; set; }
        public string SerialNumber3 { get; set; }
        public int StoreID { get; set; }
        public int TransactionEntryID { get; set; }
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string SerialNumber { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int Status { get; set; }
    }
}
