//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int ServiceID { get; set; }
        public int TransactionNumber { get; set; }
        public int OrderHistoryID { get; set; }
        public decimal Charge { get; set; }
        public string TrackingNumber { get; set; }
        public string Notes { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string EmailAddress { get; set; }
        public int Status { get; set; }
        public string CODReturnTrackingNumber { get; set; }
        public Nullable<System.DateTime> PackagingDate { get; set; }
        public decimal NetShipCost { get; set; }
        public string CarrierName { get; set; }
        public string ServiceName { get; set; }
        public double TotalWeight { get; set; }
        public decimal DeclaredValue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
    }
}
