//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipTo
    {
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Company { get; set; }
        public string Country { get; set; }
        public int CustomerID { get; set; }
        public int HQID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public int StoreID { get; set; }
        public string Zip { get; set; }
        public int ID { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
    }
}
