//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingCarrier
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string TrackingURL { get; set; }
        public string ShippingURL { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int HQID { get; set; }
        public string Code { get; set; }
    }
}
