//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingService
    {
        public int ID { get; set; }
        public int CarrierID { get; set; }
        public string Name { get; set; }
        public bool ChargeByWeight { get; set; }
        public bool Interpolate { get; set; }
        public double Value1 { get; set; }
        public decimal Charge1 { get; set; }
        public double Value2 { get; set; }
        public decimal Charge2 { get; set; }
        public double Value3 { get; set; }
        public decimal Charge3 { get; set; }
        public double Value4 { get; set; }
        public decimal Charge4 { get; set; }
        public double Value5 { get; set; }
        public decimal Charge5 { get; set; }
        public double Value6 { get; set; }
        public decimal Charge6 { get; set; }
        public double Value7 { get; set; }
        public decimal Charge7 { get; set; }
        public double Value8 { get; set; }
        public decimal Charge8 { get; set; }
        public double Value9 { get; set; }
        public decimal Charge9 { get; set; }
        public double Value10 { get; set; }
        public decimal Charge10 { get; set; }
        public double Value11 { get; set; }
        public decimal Charge11 { get; set; }
        public double Value12 { get; set; }
        public decimal Charge12 { get; set; }
        public double Value13 { get; set; }
        public decimal Charge13 { get; set; }
        public double Value14 { get; set; }
        public decimal Charge14 { get; set; }
        public double Value15 { get; set; }
        public decimal Charge15 { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int HQID { get; set; }
        public string Code { get; set; }
    }
}
