//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatureCapture
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int TenderEntryID { get; set; }
        public int ScaleWidth { get; set; }
        public int ScaleHeight { get; set; }
        public string Signature { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
