//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storeEntities : DbContext
    {
        public storeEntities(string str)
            : base(str)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounting> Accountings { get; set; }
        public virtual DbSet<AccountReceivable> AccountReceivables { get; set; }
        public virtual DbSet<AccountReceivableHistory> AccountReceivableHistories { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Alias> Aliases { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<CalendarEvent> CalendarEvents { get; set; }
        public virtual DbSet<Cashier> Cashiers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Check> Checks { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CustomButton> CustomButtons { get; set; }
        public virtual DbSet<CustomCaption> CustomCaptions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DailySale> DailySales { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<DimensionAttribute> DimensionAttributes { get; set; }
        public virtual DbSet<DropPayout> DropPayouts { get; set; }
        public virtual DbSet<Exchange> Exchanges { get; set; }
        public virtual DbSet<Import> Imports { get; set; }
        public virtual DbSet<ImportEntry> ImportEntries { get; set; }
        public virtual DbSet<InventoryOffline> InventoryOfflines { get; set; }
        public virtual DbSet<InventoryTransferLog> InventoryTransferLogs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemClass> ItemClasses { get; set; }
        public virtual DbSet<ItemClassComponent> ItemClassComponents { get; set; }
        public virtual DbSet<ItemMessage> ItemMessages { get; set; }
        public virtual DbSet<ItemTax> ItemTaxes { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Kit> Kits { get; set; }
        public virtual DbSet<LimitEntry> LimitEntries { get; set; }
        public virtual DbSet<Macro> Macroes { get; set; }
        public virtual DbSet<MacroEvent> MacroEvents { get; set; }
        public virtual DbSet<MatrixAttributeDisplayOrder> MatrixAttributeDisplayOrders { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<NetDisplayChannel> NetDisplayChannels { get; set; }
        public virtual DbSet<NetDisplayURL> NetDisplayURLs { get; set; }
        public virtual DbSet<NonTenderTransaction> NonTenderTransactions { get; set; }
        public virtual DbSet<OldJournal> OldJournals { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderEntry> OrderEntries { get; set; }
        public virtual DbSet<OrderHistory> OrderHistories { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PhysicalInventory> PhysicalInventories { get; set; }
        public virtual DbSet<PhysicalInventoryEntry> PhysicalInventoryEntries { get; set; }
        public virtual DbSet<PoleDisplayMessage> PoleDisplayMessages { get; set; }
        public virtual DbSet<PriceRounding> PriceRoundings { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderEntry> PurchaseOrderEntries { get; set; }
        public virtual DbSet<PurchaseOrderEntryDetail> PurchaseOrderEntryDetails { get; set; }
        public virtual DbSet<QuantityDiscount> QuantityDiscounts { get; set; }
        public virtual DbSet<QuoteTenderEntry> QuoteTenderEntries { get; set; }
        public virtual DbSet<ReasonCode> ReasonCodes { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RR_AppKey> RR_AppKey { get; set; }
        public virtual DbSet<RR_Application> RR_Application { get; set; }
        public virtual DbSet<RR_LoginData> RR_LoginData { get; set; }
        public virtual DbSet<RR_User> RR_User { get; set; }
        public virtual DbSet<RR_UserPrivileges> RR_UserPrivileges { get; set; }
        public virtual DbSet<RR_UserRole> RR_UserRole { get; set; }
        public virtual DbSet<RRSMTP_Configuration> RRSMTP_Configuration { get; set; }
        public virtual DbSet<SalesRep> SalesReps { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleSegment> ScheduleSegments { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<Serial> Serials { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
        public virtual DbSet<ShippingCarrier> ShippingCarriers { get; set; }
        public virtual DbSet<ShippingService> ShippingServices { get; set; }
        public virtual DbSet<ShippingWebPair> ShippingWebPairs { get; set; }
        public virtual DbSet<ShipTo> ShipToes { get; set; }
        public virtual DbSet<SignatureCapture> SignatureCaptures { get; set; }
        public virtual DbSet<Substitute> Substitutes { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierList> SupplierLists { get; set; }
        public virtual DbSet<Taskpad> Taskpads { get; set; }
        public virtual DbSet<TaskpadButton> TaskpadButtons { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TaxEntry> TaxEntries { get; set; }
        public virtual DbSet<TaxTotal> TaxTotals { get; set; }
        public virtual DbSet<Tender> Tenders { get; set; }
        public virtual DbSet<TenderDenomination> TenderDenominations { get; set; }
        public virtual DbSet<TenderEntry> TenderEntries { get; set; }
        public virtual DbSet<TimeClock> TimeClocks { get; set; }
        public virtual DbSet<TouchScreenKeyboard> TouchScreenKeyboards { get; set; }
        public virtual DbSet<TouchScreenKeyboardEntry> TouchScreenKeyboardEntries { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionEntry> TransactionEntries { get; set; }
        public virtual DbSet<TransactionHold> TransactionHolds { get; set; }
        public virtual DbSet<TransactionHoldEntry> TransactionHoldEntries { get; set; }
        public virtual DbSet<UserTopic> UserTopics { get; set; }
        public virtual DbSet<VersionHistory> VersionHistories { get; set; }
        public virtual DbSet<VisaNetAuthorization> VisaNetAuthorizations { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<VoucherEntry> VoucherEntries { get; set; }
        public virtual DbSet<AccountingAccount> AccountingAccounts { get; set; }
        public virtual DbSet<AccountingTerm> AccountingTerms { get; set; }
        public virtual DbSet<ARHistoryMirror> ARHistoryMirrors { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<DatabaseMetaData> DatabaseMetaDatas { get; set; }
        public virtual DbSet<DynamicsOnlineAuthorization> DynamicsOnlineAuthorizations { get; set; }
        public virtual DbSet<GlobalRequestlog> GlobalRequestlogs { get; set; }
        public virtual DbSet<HQMessage> HQMessages { get; set; }
        public virtual DbSet<ItemValueLog> ItemValueLogs { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }
        public virtual DbSet<RecordDeletedLog> RecordDeletedLogs { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<TaskpadLayout> TaskpadLayouts { get; set; }
        public virtual DbSet<TenderTotal> TenderTotals { get; set; }
        public virtual DbSet<TimeCard> TimeCards { get; set; }
        public virtual DbSet<TimeStampLog> TimeStampLogs { get; set; }
        public virtual DbSet<VisaNetBatch> VisaNetBatches { get; set; }
        public virtual DbSet<VoucherFormatNumber> VoucherFormatNumbers { get; set; }
    }
}
