//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string StoreCode { get; set; }
        public string Region { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string FaxNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int ParentStoreID { get; set; }
        public int ScheduleHourMask1 { get; set; }
        public int ScheduleHourMask2 { get; set; }
        public int ScheduleHourMask3 { get; set; }
        public int ScheduleHourMask4 { get; set; }
        public int ScheduleHourMask5 { get; set; }
        public int ScheduleHourMask6 { get; set; }
        public int ScheduleHourMask7 { get; set; }
        public int ScheduleMinute { get; set; }
        public int RetryCount { get; set; }
        public int RetryDelay { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public bool Inactive { get; set; }
        public bool SyncedStoreStatus { get; set; }
    }
}
