//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string Country { get; set; }
        public int HQID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string State { get; set; }
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public string ContactName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string EmailAddress { get; set; }
        public string WebPageAddress { get; set; }
        public string Code { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public string AccountNumber { get; set; }
        public string TaxNumber { get; set; }
        public int CurrencyID { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string CustomText1 { get; set; }
        public string CustomText2 { get; set; }
        public string CustomText3 { get; set; }
        public string CustomText4 { get; set; }
        public string CustomText5 { get; set; }
        public double CustomNumber1 { get; set; }
        public double CustomNumber2 { get; set; }
        public double CustomNumber3 { get; set; }
        public double CustomNumber4 { get; set; }
        public double CustomNumber5 { get; set; }
        public Nullable<System.DateTime> CustomDate1 { get; set; }
        public Nullable<System.DateTime> CustomDate2 { get; set; }
        public Nullable<System.DateTime> CustomDate3 { get; set; }
        public Nullable<System.DateTime> CustomDate4 { get; set; }
        public Nullable<System.DateTime> CustomDate5 { get; set; }
        public string Notes { get; set; }
        public string Terms { get; set; }
    }
}
