//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierList
    {
        public double MinimumOrder { get; set; }
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int SupplierID { get; set; }
        public decimal Cost { get; set; }
        public string ReorderNumber { get; set; }
        public int MasterPackQuantity { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public double TaxRate { get; set; }
    }
}
