//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskpadButton
    {
        public int ID { get; set; }
        public int TaskpadID { get; set; }
        public int Type { get; set; }
        public int FontSize { get; set; }
        public string FontName { get; set; }
        public string Color { get; set; }
        public string CaptionCustom { get; set; }
        public Nullable<int> FontOption { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ButtonIndex { get; set; }
        public string ObjectID { get; set; }
        public Nullable<int> ImageAlignment { get; set; }
        public string FontColor { get; set; }
        public Nullable<int> HQID { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
