//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public decimal FixedAmount { get; set; }
        public int HQID { get; set; }
        public int ID { get; set; }
        public string Description { get; set; }
        public float Percentage { get; set; }
        public bool UsePartialDollar { get; set; }
        public decimal ItemMaximum { get; set; }
        public bool IncludePreviousTax { get; set; }
        public decimal Bracket00 { get; set; }
        public decimal Bracket01 { get; set; }
        public decimal Bracket02 { get; set; }
        public decimal Bracket03 { get; set; }
        public decimal Bracket04 { get; set; }
        public decimal Bracket05 { get; set; }
        public decimal Bracket06 { get; set; }
        public decimal Bracket07 { get; set; }
        public decimal Bracket08 { get; set; }
        public decimal Bracket09 { get; set; }
        public decimal Bracket10 { get; set; }
        public string Code { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public decimal ItemMinimum { get; set; }
        public bool ApplyOverMinimum { get; set; }
        public decimal Bracket11 { get; set; }
        public decimal Bracket12 { get; set; }
        public decimal Bracket13 { get; set; }
        public decimal Bracket14 { get; set; }
        public decimal Bracket15 { get; set; }
        public decimal Bracket16 { get; set; }
        public decimal Bracket17 { get; set; }
        public decimal Bracket18 { get; set; }
        public decimal Bracket19 { get; set; }
        public decimal Bracket20 { get; set; }
        public decimal Bracket21 { get; set; }
        public decimal Bracket22 { get; set; }
        public decimal Bracket23 { get; set; }
        public decimal Bracket24 { get; set; }
        public decimal Bracket25 { get; set; }
        public decimal Bracket26 { get; set; }
        public decimal Bracket27 { get; set; }
        public decimal Bracket28 { get; set; }
        public decimal Bracket29 { get; set; }
        public decimal Bracket30 { get; set; }
        public decimal BracketValue01 { get; set; }
        public decimal BracketValue02 { get; set; }
        public decimal BracketValue03 { get; set; }
        public decimal BracketValue04 { get; set; }
        public decimal BracketValue05 { get; set; }
        public decimal BracketValue06 { get; set; }
        public decimal BracketValue07 { get; set; }
        public decimal BracketValue08 { get; set; }
        public decimal BracketValue09 { get; set; }
        public decimal BracketValue10 { get; set; }
        public decimal BracketValue11 { get; set; }
        public decimal BracketValue12 { get; set; }
        public decimal BracketValue13 { get; set; }
        public decimal BracketValue14 { get; set; }
        public decimal BracketValue15 { get; set; }
        public decimal BracketValue16 { get; set; }
        public decimal BracketValue17 { get; set; }
        public decimal BracketValue18 { get; set; }
        public decimal BracketValue19 { get; set; }
        public decimal BracketValue20 { get; set; }
        public decimal BracketValue21 { get; set; }
        public decimal BracketValue22 { get; set; }
        public decimal BracketValue23 { get; set; }
        public decimal BracketValue24 { get; set; }
        public decimal BracketValue25 { get; set; }
        public decimal BracketValue26 { get; set; }
        public decimal BracketValue27 { get; set; }
        public decimal BracketValue28 { get; set; }
        public decimal BracketValue29 { get; set; }
        public decimal BracketValue30 { get; set; }
    }
}
