//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderTotal
    {
        public int StoreID { get; set; }
        public int BatchNumber { get; set; }
        public int TenderID { get; set; }
        public decimal Open { get; set; }
        public decimal Shift { get; set; }
        public decimal Close { get; set; }
        public int Count { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public decimal OpenForeign { get; set; }
        public decimal CloseForeign { get; set; }
        public decimal ShiftForeign { get; set; }
        public decimal ShiftRoundingError { get; set; }
        public int ID { get; set; }
    }
}
