//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHold
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public short TransactionType { get; set; }
        public string HoldComment { get; set; }
        public int RecallID { get; set; }
        public string Comment { get; set; }
        public short PriceLevel { get; set; }
        public short DiscountMethod { get; set; }
        public double DiscountPercent { get; set; }
        public bool Taxable { get; set; }
        public int CustomerID { get; set; }
        public decimal DeltaDeposit { get; set; }
        public bool DepositOverride { get; set; }
        public decimal DepositPrevious { get; set; }
        public decimal PaymentsPrevious { get; set; }
        public decimal TaxPrevious { get; set; }
        public int SalesRepID { get; set; }
        public int ShipToID { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public System.DateTime ExpirationOrDueDate { get; set; }
        public bool ReturnMode { get; set; }
        public string ReferenceNumber { get; set; }
        public decimal ShippingChargePurchased { get; set; }
        public bool ShippingChargeOverride { get; set; }
        public int ShippingServiceID { get; set; }
        public string ShippingTrackingNumber { get; set; }
        public string ShippingNotes { get; set; }
        public byte[] DBTimeStamp { get; set; }
        public int ReasonCodeID { get; set; }
        public int ExchangeID { get; set; }
        public int ChannelType { get; set; }
        public int DefaultDiscountReasonCodeID { get; set; }
        public int DefaultReturnReasonCodeID { get; set; }
        public int DefaultTaxChangeReasonCodeID { get; set; }
        public int BatchNumber { get; set; }
    }
}
