//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaNetBatch
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> RequestTerminalNumber { get; set; }
        public Nullable<System.DateTime> RequestTransmissionDate { get; set; }
        public Nullable<int> RequestBatchNumber { get; set; }
        public string ResponseRecordFormat { get; set; }
        public string ResponseApplicationType { get; set; }
        public string ResponseX25RoutingID { get; set; }
        public string ResponseRecordType { get; set; }
        public string ResponseBatchRecordCount { get; set; }
        public Nullable<decimal> ResponseBatchNetDeposit { get; set; }
        public string ResponseBatchResponseCode { get; set; }
        public string ResponseBatchNumber { get; set; }
        public string ResponseBatchResponseText { get; set; }
        public byte[] DBTimeStamp { get; set; }
    }
}
